# Production Docker Compose pour AREA Project
version: '3.8'

services:
  frontend:
    image: area-frontend:latest
    container_name: area_frontend_prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.5'
        reservations:
          memory: 32M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:noexec,nosuid,size=100m
      - /var/run:noexec,nosuid,size=100m
      - /tmp:noexec,nosuid,size=100m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`area.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    image: area-backend:latest
    container_name: area_backend_prod
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=file:./database/prod.db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    volumes:
      - db_data:/app/prisma/database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.area.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/database

networks:
  default:
    name: area-prod-network
    driver: bridge
